const vips = [
  {
    label: "Vip Gold 15 dias",
    type: "gold",
    price: 1000,
    time: 15,
    benefits: {
      garages: 3,
      salary: 2500,
      queue: 50,
      extra1: "Não perde mochila",
    },
  },
  {
    label: "Vip Gold 30 dias",
    type: "gold",
    price: 2000,
    time: 30,
    benefits: {
      garages: 3,
      salary: 2500,
      queue: 50,
      extra1: "Não perde mochila",
    },
  },
  {
    label: "Vip Platinum 15 dias",
    type: "platinum",
    price: 3000,
    time: 15,
    benefits: {
      garages: 6,
      salary: 4000,
      queue: 90,
      extra1: "Não perde mochila",
      extra2: "Isento da Taxa da Mansão",
      extra3: "Isento da Taxa da Garagem Publica",
      extra4: "2% Taxa do IPVA",
      extra5: "Acesso Concessionária VIP",
    }, 
  },
  {
    label: "Vip Platinum 30 dias",
    type: "platinum",
    price: 5000,
    time: 30,
    benefits: {
      garages: 6,
      salary: 4000,
      queue: 90,
      extra1: "Não perde mochila",
      extra2: "Isento da Taxa da Mansão",
      extra3: "Isento da Taxa da Garagem Publica",
      extra4: "2% Taxa do IPVA",
      extra5: "Acesso Concessionária VIP",
    },
  },
];